### ISSUE TITLE
.Net Core 6 Compatibility

### ISSUE THREAD

**Issue by TRexStark** [Weberistic/uSupport#17] opened 2024-01-17 19:27 UTC
Seems that the nuget Package is compatible with .Net Core 5 only?

I tried installing it in a .Net Core 6 with Umbraco 10.8.3 but I'm getting a compatibility error.

I also noticed that your documentations state v2.0.0 where the nuget package is only v1.2.1.

Do you have plans to launch a .Net Core 6 compatible version soon?

**Comment by Lantzify** [comment] 2024-01-27 15:40
Hello! Thank you for opening an issue and bringing this to my attention!

Hmm, it should already support .net core 6. I'll have to investigate it!

I started working on v.2.0.0. But I unfortunately haven't had the time to finish it. And then I forgot about it. I believe is near completion. I'll try to get the new version done as quickly as possible!

**Comment by Lantzify** [comment] 2024-02-16 20:59
Hello again @TRexStark! I am looking into the compatible  issues. I am unable to reproduce the compatible issue you are experiencing with uSupport 1.2.1 for it  Umbraco 10.8.3. What are the steps to reproduce this?

**Comment by TRexStark** [comment] 2024-02-25 17:05
Hi @Lantzify Sorry I didn't get a chance to re-test this.

Upon installation (from nuget), I do a solution clean so I can rebuild and debug, but upon executing a clean, I get an error pointing to uSupport.targets > "ReautoDir" task was not found.

**Comment by Lantzify** [comment] 2024-02-26 11:35
Ah! Okay! That's a known error! And it's fixed in v2.0.0! I'll try to release it this week! I'll close this issue once it's released!

**Comment by TRexStark** [comment] 2024-02-26 11:38
Thanks @Lantzify

**Comment by Lantzify** [comment] 2024-03-05 20:50
2.0.0 is now released @TRexStark! Thank you for reminding me! Let me know if you need any assistance!

**Closed by Lantzify** 2024-03-05 20:50 UTC
Labels: enhancement

**Comment by TRexStark** [comment] 2024-11-06 02:18
Hi @Lantzify

Sorry I totally forgot to confirm that this works perfectly now.
